dataset: babel
exp_name: new_action_kick_class

save_model_interval: 20
nz: 128
t_his: 10
t_pred: 60
lambda_v: 1000
beta: 0.01
vae_specs:
  model_name: v4
  is_bn: true
  is_dropout: true
  rnn_type: gru
  x_birnn: false
  use_drnn_mlp: true

  # dataset
  n_action: 11
  actions: ['stand_up', 'sit_down', 'jump_forward', 'jump_jacks', 'jump_rope', 'pick_up', 'put_down', 'walk', 'walk_backwards', 'kick_right', 'kick_left']
  max_len: 80
  min_len: 30
  t_pre_extra: 50
  data_file: './data/new_action_kick_{}.npz'
  lambdas: [ 100.0, 1000.0, 1.0, 100 ]
vae_lr: 1.e-3
batch_size: 64
num_vae_epoch: 1000
num_vae_epoch_fix: 200
num_vae_data_sample: 5000
